---

trigger:
  - master

steps:
  - pwsh: |
      ./scripts/install_r.ps1
    displayName: 'Install R'
  - pwsh: |
      ./scripts/install_linters.ps1
    displayName: 'Install linters'
  - pwsh: |
      python -m yamllint --strict .
    displayName: 'Lint YAML'
  - pwsh: |
      $lintErrors = Invoke-ScriptAnalyzer -Path . -Recurse
      if ($lintErrors) {
        Write-Output $lintErrors
        Exit 1
      }
    displayName: 'Lint PowerShell'
  - pwsh: |
      $lintErrors = Rscript -e "lintr::lint_dir()"
      if ($lintErrors) {
        Write-Output $lintErrors
        Exit 1
      }
    displayName: 'Lint R'

pool:
  vmImage: 'windows-2019'
