CREATE MASTER KEY ENCRYPTION BY PASSWORD = '$(MasterKey)';

CREATE DATABASE SCOPED CREDENTIAL AzureModels
WITH IDENTITY = 'SHARED ACCESS SIGNATURE',
SECRET = '$(ModelSAS)';

CREATE EXTERNAL DATA SOURCE AzureModels WITH (
  TYPE = BLOB_STORAGE,
  LOCATION = 'https://$(StorageAccount).blob.core.windows.net',
  CREDENTIAL = AzureModels
);
